version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - 8081:8081
    environment:
      - PORT=8081
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"